### ISSUE TITLE
Slice should be splice in tuner

### ISSUE THREAD

**Issue by cmacmillan** [LeeYiyuan/tetrisai#3]
Tuner.js line 116 is candidates.slice(-newCandidates.length); But this doesn't actually do anything because slice doesn't affect the array at all and the return value just gets discarded. I think you meant to do candidates.splice(-newCandidates.length);

**Comment by LeeYiyuan** [comment]
Fixed in @163cd31

**Comment by LeeYiyuan** [comment]
Fixed in pull request #4.
