### ISSUE TITLE
Weight column heights

### ISSUE THREAD

**Issue by MrStahlfelge** [LeeYiyuan/tetrisai#5]
Thank you for this great and simple to implement AI. I integrated it in my game to let users play against a bot.
Your game doesn't spawn the pieces at the gameboard center, which is normally the case. Thus, it is a problem if the center columns are not kept empty. I found that the very simple approach of weighting the columns in a way it is avoided to fill the higher centered positions did a great job in solving this:

    private float aggregateWeightedHeight(AiGameboard gameboard) {
        float aggregateHeight = 0;

        for (int x = 0; x < Gameboard.GAMEBOARD_COLUMNS; x++) {
            // pos weight 0123454321 => 1.0, 1.07, 1.14, ...
            // the more the column is centered, the more it is avoided drop pieces
            float posWeight = 1f + Math.abs(Math.abs(x - (Gameboard.GAMEBOARD_COLUMNS / 2f)) - Gameboard.GAMEBOARD_COLUMNS / 2f) / 15f;
            int y = gameboard.getColumnHeight(x);

            aggregateHeight = aggregateHeight + y * posWeight;
        }

        return aggregateHeight;
    }

Wanted to let you know as an information and thank you.

**Comment by LeeYiyuan** [comment]
@MrStahlfelge Thank you, that's a great idea - indeed, a heuristic to encourage pieces to drop into the center does seem helpful!
